### ISSUE TITLE
[error] npm run dev 

### ISSUE THREAD

**Issue by joe223** [eteplus/vue-sui-demo#22]
已经解决

**Comment by joe223** [comment]
> vue-sui-demo@0.1.4 dev /Users/bici/Documents/test_project/vue-sui-demo
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/bici/.nvm/versions/node/v6.3.0/bin/node" "/Users/bici/.nvm/versions/node/v6.3.0/bin/npm" "run" "dev"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vue-sui-demo@0.1.4 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-sui-demo@0.1.4 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-sui-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-sui-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-sui-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bici/Documents/test_project/vue-sui-demo/npm-debug.log

**Comment by joe223** [comment]
之前的ok了，new issue
ERROR in ./src/app.js
Module build failed: Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bici/Documents/test_project/vue-sui-demo/node_modules/.npminstall/babel-runtime/6.9.2/babel-runtime/core-js/get-iterator.js:1:93)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bici/Documents/test_project/vue-sui-demo/node_modules/.npminstall/babel-types/6.11.1/babel-types/lib/index.js:6:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bici/Documents/test_project/vue-sui-demo/node_modules/.npminstall/babel-helper-get-function-arity/6.8.0/babel-helper-get-function-arity/lib/index.js:16:43)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bici/Documents/test_project/vue-sui-demo/node_modules/.npminstall/babel-helper-function-name/6.8.0/babel-helper-function-name/lib/index.js:58:60)
    at Module._compile (module.js:541:32)

**Comment by GGCarry** [comment]
怎么解决的，我也跑不起来

**Comment by joe223** [comment]
@GGCarry 看下控制台的具体报错。话说现在要看2.0啊，紧跟版本23333

**Comment by GGCarry** [comment]
C:\Users\Administrator\Desktop\vue-sui-demo-master>npm run dev

> vue-sui-demo@0.1.5 dev C:\Users\Administrator\Desktop\vue-sui-demo-master
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (C:\Users\Administrator\Desktop\vue-sui-demo-master\node_modules\express\lib\application.js:617:24)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\vue-sui-demo-master\build\dev-server.js:57:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! vue-sui-demo@0.1.5 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-sui-demo@0.1.5 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-sui-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-sui-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-sui-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\vue-sui-demo-master\npm-debug.log

报这样的错，不知道怎么搞，我的就是2.0的，大神帮我解决下

**Comment by joe223** [comment]
@GGCarry 应该是`8080`端口被占用，试试改下`vue-sui-demo/config/index.js`中的
```
dev: {
    env: require('./dev.env'),
    port: 8080,    // 改成其他的，eg:8081
    proxyTable: {}
  }
```
